name: CI

on:
  pull_request:
    branches: 
      - main

  workflow_dispatch:

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Installing dependencies
        run: npm i
      - name: Run linting
        run: npm run lint
      - name: Run test
        run: npm run test
      - name: Run build
        run: npm run build